<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LifeOS.Domain\LifeOS.Domain.csproj" />
    <ProjectReference Include="..\LifeOS.Infrastructure\LifeOS.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

  <Target Name="CopyBlazorRuntimeForLocalRun" AfterTargets="Build">
    <MakeDir Directories="$(OutputPath)wwwroot\framework" />
    <Copy SourceFiles="$(BlazorFrameworkStaticWebAssetRoot)\blazor.web.js"
          DestinationFiles="$(OutputPath)wwwroot\framework\blazor.web.js" />
  </Target>

  <Target Name="CopyBlazorRuntimeForPublish" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)wwwroot\framework" />
    <Copy SourceFiles="$(BlazorFrameworkStaticWebAssetRoot)\blazor.web.js"
          DestinationFiles="$(PublishDir)wwwroot\framework\blazor.web.js" />
  </Target>

</Project>
